#This Sript find Expired ssl certs on current host only
# by Armando Zincke 
# 7/18/2019
#########################################

Get-ChildItem cert:\ -Recurse | Where-Object {$_ -is [System.Security.Cryptography.X509Certificates.X509Certificate2] -and $_.NotAfter -lt (Get-Date)} | Select-Object -Property FriendlyName,NotAfter | ConvertTo-Html | Set-Content C:\Temp\ExpiredCerts001.html

$y = Get-Date -format yyyy
$m = Get-Date -format MM
$d = Get-Date -format dd
$h = Get-Date -format 05
#################################### 

$EmailTo = "armando.zincke@gmail.com"
$EmailFrom = "armando.zincke@outlook.com"
$Subject = “ExpiredCerts on $(($env:COMPUTERNAME))”
$Body = “ This Email was generated by a powershell script on $((Get-Date))”
$SMTPServer = "smtp.live.com" 
$filenameAndPath = "C:\Temp\ExpiredCerts001.html"
$SMTPMessage = New-Object System.Net.Mail.MailMessage($EmailFrom,$EmailTo,$Subject,$Body)
$attachment = New-Object System.Net.Mail.Attachment($filenameAndPath)
$SMTPMessage.Attachments.Add($attachment)
$SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587) 
$SMTPClient.EnableSsl = $true 
$SMTPClient.Credentials = New-Object System.Net.NetworkCredential(“email”, “passwor”); 
$SMTPClient.Send($SMTPMessage)





 
